name: Update README ⭐
on: push
jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: k2bd/advent-readme-stars@v1
        with:
          tableMarker: "<!--- advent_readme_stars table 2021 --->"
          userId: 420921
          sessionCookie: ${{ secrets.AOC_SESSION }}
          year: 2021
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update README stars
